config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :show, :destroy]
  devise_for :users
  resources :food, only: %i[index show new create destroy]
  resources :recipe_foods, only: %i[destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'public_recipe', to: 'recipes#public_recipe', as: :public_recipe
  get 'shopping_list', to: 'users#shopping_list', as: :shopping_list

  # Defines the root path route ("/")
  root to: "food#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(post_params)
    if @food.save
      redirect_to root_path
    else
      redirect_to :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:notice] = 'The food item was successfully deleted.'
    redirect_to root_path
  end

  private

  def post_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find(@recipe_food.recipe_id)
    @recipe_food.destroy
    flash[:notice] = 'The ingredient was successfully deleted.'
    redirect_to recipe_path(recipe)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show public_recipe]

  def index
    if current_user
      @recipes = current_user.recipes
    else
      redirect_to public_recipe_path
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  def public_recipe
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  def destroy
    recipe_foods = RecipeFood.where(recipe_id: params[:id])
    recipe_foods.each(&:destroy)
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'The recipe was successfully deleted.'
    redirect_to recipes_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def shopping_list
    @recipe_foods = RecipeFood.includes(:food).where(recipe_id: params[:recipe])
    @total = 0
    @recipe_foods.each do |rf|
      @total += rf.food.price * rf.quantity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/food/index.html.erb
<% if user_signed_in? %>
    <%= button_to "Add Food", new_food_path, method: :get, class: "btn btn-primary"  %>
<%end%>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Food</th>
            <th scope="col">Measurment Unit</th>
            <th scope="col">Unit Price </th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @foods.each do |food| %>
            <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.price %></td>
            <td> <%= button_to "Delete", food_path(food), method: :delete, class: "btn btn-danger" %> </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/food/new.html.erb
<h2> Add New Food </h2>
<%= form_with model: @food, url: food_index_path, data: { turbo: false} do |form| %>
        <% if @food.errors.any? %>
            <div class="alert alert-danger">
                <% @food.errors.full_messages do |message| %>
                    <div> <%= message %> </div>
                <% end %>
            </div>
        <% end %>
        <div class="mb-3">
            <%= form.label :name, class: "form-label" %>
            <%= form.text_field :name, class: "form-control", id: "exampleFormControlInput1", placeholder: "Food Name" %>
        </div>
        <div class="mb-3">
            <%= form.label :measurement_unit, class: "form-label" %>
            <%= form.select(:measurement_unit, options_for_select([["Grams", "g"], ["Kilogram", "kg"], ["units", "u"]], "u"), class: "form-select", id:"sss")%>
        </div>
        <div class="mb-3">
            <%= form.label :price, class: "form-label" %>
            <%= form.number_field :price, class: "form-control", id: "exampleFormControlInput1", placeholder: "Food Price" %>
        </div>
        <%= form.submit "Add Food", class:"btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </head>

  <body>
      <%= render partial: "shared/navbar" %>

   <main class="container">
    <% if notice %>
    <div class="alert alert-info"> <%= notice %> </div>
    <% end %>

    <% if alert %>
    <div class="alert alert-warning"> <%= alert %> </div>
    <% end %>
    <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/food/index.html.erb
<p> Hello Homepage </p>

app/views/recipe_foods/destroy.html.erb
<h1>RecipeFoods#destroy</h1>
<p>Find me in app/views/recipe_foods/destroy.html.erb</p>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <div class="card w-75">
      <a href="<%= recipe_path(recipe) %>">
        <div class="card-body">
          <h5 class="card-title"><%= recipe.name %></h5>
          <p class="card-text"><%= recipe.description %></p>
        </div>
      </a>
      <%= button_to "Delete", recipe_path(recipe), method: :delete, class: "btn btn-danger" %>
    </div>
    <br>
  <% end %>
</div>

app/views/recipes/public_recipe.html.erb
<h1>Public recipes</h1>

<% @recipes.each do |recipe| %>
  <a href="<%= recipe_path(recipe) %>">
    <div class="card" style="width: 18rem;">
      <div class="list-group list-group-flush">
        <h3 class="list-group-item"><%= recipe.name %></h3>
        <p class="list-group-item"><%= recipe.description %></p>
        <h5 class="list-group-item"><%= recipe.user.name %></h5>
      </div>
    </div>
  </a>
<% end %>

app/views/recipes/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @recipe.name %></h5>
    <p class="card-text">Cooking Time: <%= @recipe.cooking_time %></p>
    <p class="card-text">preparation Time: <%= @recipe.preparation_time %></p>
    <a href="<%= shopping_list_path(recipe: @recipe) %>" class="btn btn-success">Generate shopping list</a><br><br>
    <a href="" class="btn btn-primary">Add ingredient</a>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit Price </th>
        <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
      <% @recipe_foods.each do |recipe_food| %>
          <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= "#{recipe_food.quantity} #{recipe_food.food.measurement_unit}" %></td>
          <td><%= recipe_food.food.price %></td>
          <td><%= button_to "Delete", recipe_food_path(recipe_food), method: :delete, class: "btn btn-danger" %> </td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "RecipeApp", root_path, class: "navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item">
              <%= link_to "Foods", food_index_path, class: "nav-link"  %>
          </li>
          <li class="nav-item">
              <%= link_to "Recipes", recipes_path, class: "nav-link"  %>
          </li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link"  %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %>
          </li>
          <li class="nav-item">
              <%= link_to "Log In", new_user_session_path, class: "nav-link"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/shopping_list.html.erb
<h1>Shopping list</h1>

<p>Amount of items needed: <%= @recipe_foods.length %></p>
<p>Total price: <%= @total %></p>

<table class="table">
  <thead>
    <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Price </th>
    </tr>
  </thead>
  <tbody>
      <% @recipe_foods.each do |rf| %>
          <tr>
          <td><%= rf.food.name %></td>
          <td><%= rf.quantity %></td>
          <td><%= rf.food.price * rf.quantity %></td>
          </tr>
      <% end %>
  </tbody>
</table>